### ISSUE TITLE
방에서 나가는게 불편합니다

### ISSUE THREAD

**Issue by CazNm** [jiho5993/open_source_chat_B-02#10]
채팅방에서 나갈때 새로고침이나 창을 끄지 않으면 나갈 수 가 없습니다. 나가기 버튼을 만들어 주세요 ㅠㅠ

**Comment by jiho5993** [comment]
https://github.com/jiho5993/open_source_chat_B-02/commit/34dab800681bf2e9b44628e94bc355f4dac14ea0
기능을 개설하였습니다.
