### ISSUE TITLE
나중에 들어온 유저의 이름이 먼저 들어온 유저의 이름과 겹치게 됩니다.

### ISSUE THREAD

**Issue by jiho5993** [jiho5993/open_source_chat_B-02#12]
로컬이나 서버에서 나중에 들어온 유저의 이름이 먼저 들어온 유저가 방을 퇴장할때 이름이 겹치는 현상이 나타납니다. 수정해주셨으면 좋겠습니다.

**Comment by CazNm** [comment]
320b3392dbe769fcacd76d71ae5a9a27e3dc619b
사용자 데이터를 쿠키로 보내서 해결 하였습니다.
