### ISSUE TITLE
로그인 중복 방지 기능이 제대로 작용하지 않습니다.

### ISSUE THREAD

**Issue by CazNm** [jiho5993/open_source_chat_B-02#13]
로그인 중복이 한번 로그인을 완료하면 계속 적용이되어 원래의 의도한 기능대로 작동하지 않습니다. 다시 수정해주세요

**Comment by jiho5993** [comment]
https://github.com/jiho5993/open_source_chat_B-02/commit/01961368748d427459b4855a510b3bdfb0377477
해결하였습니다.
