### ISSUE TITLE
백엔드의 기초적인 기능이 필요합니다.

### ISSUE THREAD

**Issue by CazNm** [jiho5993/open_source_chat_B-02#4]
기능 개발이 하나도 되어 있지 않아서 프론트의 레이아웃을 잡기 힘듭니다. 벡엔드가 어느정도 완성되면 커밋해 주세요

**Comment by jiho5993** [comment]
https://github.com/jiho5993/open_source_chat_B-02/commit/d69c1730fc2c237dd8105c97c083c053e41e4f3e
로그인 기능과 채팅에 대한 기본적인 기능을 구현해 놓았습니다.
