### ISSUE TITLE
채팅방이 필요합니다

### ISSUE THREAD

**Issue by CazNm** [jiho5993/open_source_chat_B-02#6]
로비에 채팅방 레이아웃만 정해놓기에는 채팅창도 같이 만들어야해서 채팅방이 개설되어 있으면 좋겠습니다. 빠르게 구현해주시면 감사하겠습니다.

**Comment by jiho5993** [comment]
https://github.com/jiho5993/open_source_chat_B-02/commit/0b1a01f064fb4fdd85d43cee18e3f0991a4a40cb
구현하였습니다.
