### ISSUE TITLE
완성된 데모 버전

### ISSUE THREAD

**Issue by CazNm** [jiho5993/open_source_chat_B-02#7]
현재 백엔드와 프론트엔드가 거의 연결된 상태인데 프론트 점검을 위해서 어느정도 완성된 데모버전이 필요합니다. 완성해 주셨으면 좋겠습니다.

**Comment by jiho5993** [comment]
https://github.com/jiho5993/open_source_chat_B-02/commit/b575b51617057b8d426147e623f8f758cdb5b86e
채팅기능에 있어 전반적인 기능을 모두 구현하였습니다. 또한 데모 버전을 올려두었습니다.
