### ISSUE TITLE
방의 정보와 사용자의 정보가 넘어가지 않습니다.

### ISSUE THREAD

**Issue by jiho5993** [jiho5993/open_source_chat_B-02#9]
개설된 방에 입장시 그 다음 페이지에 사용자의 정보와 방의 정보가 넘어가지 않습니다. 빠른 해결 부탁드립니다.

**Comment by CazNm** [comment]
ac0b58cf05f3b670b86e663abc696a105b21b71f
해결했습니다. 조장님.
